import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {DarkThemeSwitcher} from "@/components/UI/DarkThemeSwitcher";
import {useContext} from "react";
import {ThemeContext} from "@/components/UI/Theme";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

    const {theme} = useContext(ThemeContext)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <DarkThemeSwitcher />
          {theme}
      </main>
    </>
  )
}
